//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""41aa9e40-40c2-4624-9e9a-79a1c260c6ae"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a2369099-6156-4aea-b193-afec1dda5128"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""92210b46-cf2e-4830-8737-d744595cd51b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c32ff950-897a-42e5-b24b-b41cda3676e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_Light"",
                    ""type"": ""Button"",
                    ""id"": ""963bb1ce-7c0d-4653-b008-92e452bfaa3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_Heavy"",
                    ""type"": ""Button"",
                    ""id"": ""b7f64f2e-6693-4c02-88a4-8df3d6427bb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_Up"",
                    ""type"": ""Button"",
                    ""id"": ""59845f30-8e9b-41c1-888d-35ee699fd1fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_Down"",
                    ""type"": ""Button"",
                    ""id"": ""c48538a2-ec82-4a6f-8121-7b85a945479a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_Front"",
                    ""type"": ""Button"",
                    ""id"": ""807de504-a970-486b-bf9c-667d5df25df2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_Ultimate"",
                    ""type"": ""Button"",
                    ""id"": ""b197772b-f8cd-4978-a047-524e4f3f3cbf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f5cce760-0f2b-4950-a025-575c101234a0"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e25188ef-ae5e-4c78-81da-b92bd6232d60"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7b0d5c3c-d5de-4964-82de-1ed7ab8c4aac"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d31649f7-062c-4726-8cea-621b0c602b29"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1380bd16-2b9d-4f73-bbed-1916908b09ab"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""04e51858-ad98-4ad3-b1b6-2c9162950103"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""759c094b-d559-4b93-a001-baaac93da11b"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d9c3e8e-9228-49a1-90a6-7157da6b3cfc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb429d94-df35-410c-ba4a-c65493782e01"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""5f1a1594-2465-4a6b-8aba-bcb058d59a9c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Up"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""5f376b18-751e-4937-9727-fcf6fcc6c492"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a1d9f500-f888-4a1f-bb41-78b7c84966df"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""8dfda713-3d7e-4a5b-b31c-1b1aa4c342af"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Down"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a534241f-76a0-4837-ae23-3ba9062da7f9"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""fc86e509-130a-42a6-9e06-1d823ab73b60"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ac15e4f0-56e3-4d99-8c5e-9d4eb4ccd4da"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""78d71beb-d7e7-49a3-b5f1-b5600c9d42a7"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Front"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""eec76f78-eacc-421a-a131-001e776f30d9"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Front"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""016245cb-a7de-4d12-97c2-40d66db51047"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Front"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""d7d60c75-65c6-4dde-af39-eadbed4b651a"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Front"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""add4fb31-9b6b-4dfd-adbd-b998d5aaf751"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Front"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5a527ef8-c5d0-4949-9728-2e8ec49660e2"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Front"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e5516c11-362a-4d63-9eec-a839f43e2ddc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""586b0c98-03e4-47c2-b5a9-04ac5993f0bc"",
            ""actions"": [
                {
                    ""name"": ""Resume"",
                    ""type"": ""Button"",
                    ""id"": ""cf341249-167b-4bc8-8a2e-e076c65aa92e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ed0d3106-f2b2-4e40-8a59-d3aab7b12f16"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""106da669-77c1-4f37-9bc3-2edf53488155"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_Jump = m_GamePlay.FindAction("Jump", throwIfNotFound: true);
        m_GamePlay_Move = m_GamePlay.FindAction("Move", throwIfNotFound: true);
        m_GamePlay_Pause = m_GamePlay.FindAction("Pause", throwIfNotFound: true);
        m_GamePlay_Attack_Light = m_GamePlay.FindAction("Attack_Light", throwIfNotFound: true);
        m_GamePlay_Attack_Heavy = m_GamePlay.FindAction("Attack_Heavy", throwIfNotFound: true);
        m_GamePlay_Attack_Up = m_GamePlay.FindAction("Attack_Up", throwIfNotFound: true);
        m_GamePlay_Attack_Down = m_GamePlay.FindAction("Attack_Down", throwIfNotFound: true);
        m_GamePlay_Attack_Front = m_GamePlay.FindAction("Attack_Front", throwIfNotFound: true);
        m_GamePlay_Attack_Ultimate = m_GamePlay.FindAction("Attack_Ultimate", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Resume = m_UI.FindAction("Resume", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private IGamePlayActions m_GamePlayActionsCallbackInterface;
    private readonly InputAction m_GamePlay_Jump;
    private readonly InputAction m_GamePlay_Move;
    private readonly InputAction m_GamePlay_Pause;
    private readonly InputAction m_GamePlay_Attack_Light;
    private readonly InputAction m_GamePlay_Attack_Heavy;
    private readonly InputAction m_GamePlay_Attack_Up;
    private readonly InputAction m_GamePlay_Attack_Down;
    private readonly InputAction m_GamePlay_Attack_Front;
    private readonly InputAction m_GamePlay_Attack_Ultimate;
    public struct GamePlayActions
    {
        private @GameInput m_Wrapper;
        public GamePlayActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_GamePlay_Jump;
        public InputAction @Move => m_Wrapper.m_GamePlay_Move;
        public InputAction @Pause => m_Wrapper.m_GamePlay_Pause;
        public InputAction @Attack_Light => m_Wrapper.m_GamePlay_Attack_Light;
        public InputAction @Attack_Heavy => m_Wrapper.m_GamePlay_Attack_Heavy;
        public InputAction @Attack_Up => m_Wrapper.m_GamePlay_Attack_Up;
        public InputAction @Attack_Down => m_Wrapper.m_GamePlay_Attack_Down;
        public InputAction @Attack_Front => m_Wrapper.m_GamePlay_Attack_Front;
        public InputAction @Attack_Ultimate => m_Wrapper.m_GamePlay_Attack_Ultimate;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void SetCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnJump;
                @Move.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnMove;
                @Pause.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPause;
                @Attack_Light.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Light;
                @Attack_Light.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Light;
                @Attack_Light.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Light;
                @Attack_Heavy.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Heavy;
                @Attack_Heavy.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Heavy;
                @Attack_Heavy.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Heavy;
                @Attack_Up.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Up;
                @Attack_Up.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Up;
                @Attack_Up.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Up;
                @Attack_Down.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Down;
                @Attack_Down.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Down;
                @Attack_Down.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Down;
                @Attack_Front.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Front;
                @Attack_Front.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Front;
                @Attack_Front.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Front;
                @Attack_Ultimate.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Ultimate;
                @Attack_Ultimate.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Ultimate;
                @Attack_Ultimate.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAttack_Ultimate;
            }
            m_Wrapper.m_GamePlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Attack_Light.started += instance.OnAttack_Light;
                @Attack_Light.performed += instance.OnAttack_Light;
                @Attack_Light.canceled += instance.OnAttack_Light;
                @Attack_Heavy.started += instance.OnAttack_Heavy;
                @Attack_Heavy.performed += instance.OnAttack_Heavy;
                @Attack_Heavy.canceled += instance.OnAttack_Heavy;
                @Attack_Up.started += instance.OnAttack_Up;
                @Attack_Up.performed += instance.OnAttack_Up;
                @Attack_Up.canceled += instance.OnAttack_Up;
                @Attack_Down.started += instance.OnAttack_Down;
                @Attack_Down.performed += instance.OnAttack_Down;
                @Attack_Down.canceled += instance.OnAttack_Down;
                @Attack_Front.started += instance.OnAttack_Front;
                @Attack_Front.performed += instance.OnAttack_Front;
                @Attack_Front.canceled += instance.OnAttack_Front;
                @Attack_Ultimate.started += instance.OnAttack_Ultimate;
                @Attack_Ultimate.performed += instance.OnAttack_Ultimate;
                @Attack_Ultimate.canceled += instance.OnAttack_Ultimate;
            }
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Resume;
    public struct UIActions
    {
        private @GameInput m_Wrapper;
        public UIActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Resume => m_Wrapper.m_UI_Resume;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Resume.started -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
                @Resume.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
                @Resume.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Resume.started += instance.OnResume;
                @Resume.performed += instance.OnResume;
                @Resume.canceled += instance.OnResume;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IGamePlayActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnAttack_Light(InputAction.CallbackContext context);
        void OnAttack_Heavy(InputAction.CallbackContext context);
        void OnAttack_Up(InputAction.CallbackContext context);
        void OnAttack_Down(InputAction.CallbackContext context);
        void OnAttack_Front(InputAction.CallbackContext context);
        void OnAttack_Ultimate(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnResume(InputAction.CallbackContext context);
    }
}
